#include<bits/stdc++.h>
using namespace std;
using ll = long long;
using i128 = __int128;

// PE 941: de Bruijn's Combination Lock / 德布鲁因的组合锁
//
// Digital combination lock with k buttons (0 to k-1, k ≤ 10).
// Lock opens when the last n buttons pressed match the preset combination.
// de Bruijn creates a sequence containing every possible n-length combination.
// C(k,n) = lexicographically smallest shortest sequence.
//
// C(3,2) = 0010211220.
//
// a_0 = 0, a_n = (920461·a_{n-1} + 800****7569) mod 10^12 for n > 0.
// Each a_n interpreted as 12-digit combination (with leading zeros).
//
// p_n = rank of a_n among a_1,…,a_N by appearance in C(10,12).
// F(N) = Σ p_n·a_n.
// Given: a_1 = 800217387569, a_2 = 696996536878, F(2) = 2194210461325,
// F(10) = 32698850376317.
// Find F(10^7) mod 1234567891.
//
// Key observations:
// - C(k,n) is a de Bruijn sequence of order n over alphabet of size k.
// - A de Bruijn sequence B(k,n) has length k^n + n - 1.
// - Lyndon words / Martin's algorithm generates lexicographically smallest
//   de Bruijn sequence (the "Ford sequence" or "granddaddy").
// - The lexicographically smallest de Bruijn sequence is generated by
//   the FKM algorithm (Fredricksen-Kessler-Maiorana) using Lyndon words.
//
// - The rank p_n of a combination in C(10,12): this is the position where
//   the 12-digit string first appears as a substring of C(10,12).
//
// - Since we're working with 10^12 possible combinations, N = 10^7 means
//   only 10^7 / 10^12 = very sparse sampling.
//
// - The partial constant 800****7569: the missing 4 digits matter.
//   We need the exact value: 800217387569 seems to be the first a_1.
//   From the recurrence: a_1 = 920461·a_0 + C mod 10^12.
//   With a_0=0, a_1 = C mod 10^12 = 800217387569.
//   So the constant C = 800217387569.
//
// - The problem asks for the order of appearance in the lexicographically
//   smallest de Bruijn sequence. This is equivalent to the lexicographic
//   rank of each 12-digit string as a substring.
//
// - The first occurrence position of a string s in the Ford de Bruijn
//   sequence is related to the Lyndon word rank of s.
//
// PE answer: (to be computed)

const ll PE_ANSWER = 0; // placeholder
const ll MOD = 1234567891LL;
const ll MOD_A = 1000000000000LL; // 10^12

// ---------- de Bruijn Sequence Generation ----------

// Generate C(k,n) - the lexicographically smallest de Bruijn sequence
// Using FKM algorithm with Lyndon words.

// For this problem, we don't need the full sequence (10^12 long).
// We need the first occurrence position of each combination.

// The lexicographically smallest de Bruijn sequence starts with n zeros.
// The first occurrence of a combination = its rank in the Lyndon word
// concatenation order.

// Martin's algorithm / Ford sequence:
// C(k,n) is the concatenation of all Lyndon words of length dividing n
// in lexicographic order, then truncated to length k^n + n - 1.

// But we only need the first occurrence position of each combination.
// For the granddaddy de Bruijn sequence, the first occurrence of a
// length-n string w is:
//   If w is a Lyndon word: position = sum of lengths of all Lyndon words
//     lexicographically smaller than w (of lengths dividing n).
//   Otherwise: the first occurrence is the same as the first occurrence
//     of the Lyndon word that is the lexicographically smallest rotation of w.

// More precisely: In the FKM de Bruijn sequence, the position of the first
// occurrence of an n-mer w is:
//   Let w' be the lexicographically smallest rotation of w.
//   If w' is primitive (period exactly n), then w' is a Lyndon word.
//   The position = Σ_{v < w'} |v| where v runs over all Lyndon words of
//   length dividing n, minus (n - 1) for the overlap at the start:
//   Actually, the position is: p(w) = Σ_{v < w'} len(v) + 1.
//   But this counts from the start. The sequence starts with n zeros.
//
// For this problem with k=10, n=12:
// The number of Lyndon words of length dividing 12 over alphabet size 10:
//   Necklace count: N(d) = (1/d) Σ_{e|d} μ(e) · k^{d/e}
//   This is also the number of Lyndon words of length exactly d.
// Total length = Σ_{d|12} d · N(d) = 10^12. ✓

// So we need to compute the Lyndon rank of each a_n mod 10^12,
// then compute F(N) = Σ p_n · a_n.

// But N = 10^7, each computation involves finding the rank among
// 10^12 strings. We need an efficient method.

// Key optimization: the rank of a 12-digit combination in the Lyndon
// word ordering is essentially its value as a base-10 number, but
// with special handling for non-primitive strings.

// Actually, for strings of fixed length n, the Lyndon rank can be
// computed by counting necklaces (aperiodic + periodic) smaller than
// the given string.

// Let's think about this differently. The de Bruijn sequence C(10,12)
// has exactly one occurrence of each 12-digit string as a cyclic
// substring (the de Bruijn property). 

// The first occurrence of w in C(10,12):
// Let w* = lexicographically smallest cyclic rotation of w.
// Let L(w*) be the rank of w* among all Lyndon words of length
// dividing 12 (in lexicographic order).
// Then position(w) = Σ_{i=1}^{L(w*)-1} len_i + 1.
// Where len_i are the lengths of Lyndon words in order.

// But note: the sequence is k^n + n - 1 long and wraps around.
// Actually, every n-mer appears exactly once in the de Bruijn sequence
// (as a window of length n sliding across the k^n+n-1 positions).

// In the FKM sequence, the n-mers appear in a specific order determined
// by their least lexicographic rotation.

// For k=10, n=12, we need to compute ranks efficiently.
// Since n=12 is small, the period can be 1,2,3,4,6,12 (divisors of 12).
// We can classify each 12-digit string by its period and smallest rotation.

// ---------- Implementation ----------

// Compute the smallest cyclic rotation (Lyndon word) of a string
// represented as a 12-digit number.
string num_to_str(ll x) {
    string s(12, '0');
    for (int i = 11; i >= 0; i--) {
        s[i] = '0' + (x % 10);
        x /= 10;
    }
    return s;
}

ll str_to_num(const string& s) {
    ll x = 0;
    for (char c : s) x = x * 10 + (c - '0');
    return x;
}

// Returns the minimal period of s
int min_period(const string& s) {
    int n = s.size();
    for (int p = 1; p <= n; p++) {
        if (n % p != 0) continue;
        bool ok = true;
        for (int i = p; i < n; i++)
            if (s[i] != s[i-p]) { ok = false; break; }
        if (ok) return p;
    }
    return n;
}

// Lexicographically smallest rotation (Lyndon word)
string min_rotation(const string& s) {
    int n = s.size();
    string best = s;
    for (int i = 1; i < n; i++) {
        string rot = s.substr(i) + s.substr(0, i);
        if (rot < best) best = rot;
    }
    return best;
}

// Count Lyndon words of length d over alphabet size k that are
// lexicographically smaller than given string w (of length d).
ll count_lyndon_smaller(const string& w, int k) {
    int d = w.size();
    // Use the formula: number of necklaces = (1/d) Σ_{e|d} φ(e)·k^{d/e}
    // For Lyndon words: we need to count aperiodic necklaces.
    
    // The set of length-d strings smaller than w can be counted
    // by considering the prefix tree (trie) of all strings.
    // This is essentially: for each position i, count strings that
    // match w[0..i-1] and have a smaller digit at position i.
    
    // But we also need to enforce that the string is a Lyndon word
    // (strictly smaller than all its proper rotations, and primitive).
    
    // For small d=12, we can enumerate all possibilities or use DP.
    // Since k=10, total strings = 10^12 which is too many to enumerate.
    // But the Lyndon words count is: (1/d) Σ_{e|d} μ(e)·k^{d/e} ≈ 10^12/12.
    // Still too many.
    
    // Better approach: use generating functions for Lyndon words.
    // The number of Lyndon words of length d starting with prefix p
    // can be computed using inclusion-exclusion / necklaces.
    
    return 0; // placeholder
}

void verify() {
    cout << "PE 941: de Bruijn's Combination Lock / 德布鲁因的组合锁\n\n";
    
    cout << "=== Problem Summary ===\n";
    cout << "C(k,n) = lexicographically smallest de Bruijn sequence.\n";
    cout << "C(3,2) = 0010211220.\n";
    cout << "a_n generated by LCG: a_n = 920461·a_{n-1}+800217387569 mod 10^12.\n";
    cout << "p_n = rank of a_n among a_1..a_N in C(10,12) order.\n";
    cout << "F(N) = Σ p_n · a_n.\n";
    cout << "Given F(2)=2194210461325, F(10)=32698850376317.\n";
    cout << "Find F(10^7) mod 1234567891.\n\n";
    
    cout << "=== Key Concepts ===\n";
    cout << "1. de Bruijn sequence B(k,n): cyclic sequence of length k^n\n";
    cout << "   containing each n-mer exactly once.\n";
    cout << "2. The Ford sequence (FKM algorithm) generates the lexicographically\n";
    cout << "   smallest de Bruijn sequence by concatenating Lyndon words.\n";
    cout << "3. For C(10,12): sequence length = 10^12 + 11.\n\n";
    
    cout << "=== Lyndon Word Approach ===\n";
    cout << "The first occurrence of w in C(10,12):\n";
    cout << "  - Find w* = lexicographically smallest rotation of w\n";
    cout << "  - w* is a Lyndon word (if w is primitive) or has period p\n";
    cout << "  - Position = sum of lengths of all Lyndon words < w*\n\n";
    
    cout << "=== Computation Strategy ===\n";
    cout << "For N=10^7, we need to compute p_n efficiently.\n";
    cout << "Since n=12 is small, we can precompute the rank of each\n";
    cout << "12-digit combination by iterating over the 10^12 strings?\n";
    cout << "No — 10^12 is too large. Need smarter enumeration.\n\n";
    
    cout << "The rank of a string is essentially its value in a specific\n";
    cout << "base-10 ordering, adjusted for non-primitive strings.\n";
    cout << "The total ordering is: all length-1 Lyndon words (digits 0-9),\n";
    cout << "then length-2, length-3, length-4, length-6, length-12.\n\n";
    
    cout << "=== PE Answer ===\n" << PE_ANSWER << "\n";
}

int main() {
    ios::sync_with_stdio(false); cin.tie(0);
    string query;
    getline(cin, query);
    
    if (query == "PE") { cout << PE_ANSWER << "\n"; return 0; }
    if (query == "verify") { verify(); return 0; }
    cout << "PE 941: de Bruijn's Combination Lock / 德布鲁因的组合锁\n";
    cout << "Answer = " << PE_ANSWER << "\n";
    cout << "Use 'PE' for answer, 'verify' for checks.\n";
    return 0;
}
