#include<bits/stdc++.h>
using namespace std;

#define ll long long

// PE 138: Isosceles triangles with h = b ± 1
// b = 2k, L^2 = k^2 + (2k ± 1)^2 = 5k^2 ± 4k + 1
// Multiply by 5: 5L^2 = 25k^2 ± 20k + 5 = (5k ± 2)^2 + 1
// So (5k ± 2)^2 - 5L^2 = -1 => x^2 - 5y^2 = -1 (Pell equation)
// Solutions generated by recurrence from (2,1):
// x_{n+1} = 9x_n + 20y_n, y_{n+1} = 4x_n + 9y_n
// L = y, valid when x ≡ 2 or 3 (mod 5) and x > 2

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int K;
    cin >> K;

    ll x = 2, y = 1;  // fundamental solution to x^2 - 5y^2 = -1
    ll sum = 0;
    int cnt = 0;

    while (cnt < K) {
        // generate next solution
        ll nx = 9 * x + 20 * y;
        ll ny = 4 * x + 9 * y;
        x = nx;
        y = ny;

        // check if this gives valid triangle: x ≡ 2 or 3 (mod 5) and x > 2
        if (x % 5 == 2 || x % 5 == 3) {
            sum += y;
            cnt++;
        }
    }

    cout << sum << "\n";
    return 0;
}
