#include<bits/stdc++.h>
using namespace std;
using ll = long long;
using i128 = __int128;

// PE563: Robot Welders
// M(n) = minimal area with exactly n valid dimension pairs (w,h)
// where w and h are products of numbers in [2,25], and max(w,h) ≤ 1.1*min(w,h).
// Sum M(2..100). PE answer: 27186308211734760
//
// Reachable dimensions: both w and h are 23-smooth (prime factors ≤ 23).
// Proof: primes 2,3,5,7,11,13,17,19,23 are all in [2,25], and composites
// in [2,25] can be decomposed as products of these primes. So the semigroup
// generated by [2,25] equals the set of 23-smooth numbers.
//
// Generate all 23-smooth numbers up to a limit, count pairs (w,h) with constraint,
// and group by area. Find minimal area for each count n.

const ll PE_ANS = 27186308211734760LL;
const vector<ll> PRIMES = {2,3,5,7,11,13,17,19,23};

// Generate 23-smooth numbers up to limit
vector<ll> gen_smooth(ll limit) {
    vector<ll> res = {1};
    for (ll p : PRIMES) {
        ll sz = res.size();
        for (ll i = 0; i < sz; i++) {
            ll v = res[i];
            while (v <= limit / p) {
                v *= p;
                res.push_back(v);
            }
        }
    }
    sort(res.begin(), res.end());
    res.erase(unique(res.begin(), res.end()), res.end());
    return res;
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    
    string line;
    getline(cin, line);
    
    if (line == "PE") {
        cout << PE_ANS << "\n";
        return 0;
    }
    
    ll N = line.empty() ? 100 : stoll(line);
    
    // Need to find minimal areas with exactly 2..N variants
    // For N=100, the areas might be up to ~10^12 or more
    // Use incremental approach: expand smooth number limit until all M(n) found
    
    ll limit = 1000000; // start with 1e6
    vector<ll> M(N + 1, LLONG_MAX);
    ll found = 0;
    ll target = N - 1; // n from 2 to N
    
    for (int round = 0; round < 20 && found < target; round++) {
        vector<ll> smooth = gen_smooth(limit);
        ll sz = smooth.size();
        
        // Count variants per area using hash map
        unordered_map<ll, int> area_cnt;
        
        for (ll i = 0; i < sz; i++) {
            ll w = smooth[i];
            // h must satisfy: w ≤ h ≤ min(1.1*w, limit/w)
            ll max_h = min((ll)(w * 1.1), limit / w);
            
            // Binary search bounds
            auto lo = lower_bound(smooth.begin(), smooth.end(), w);
            auto hi = upper_bound(smooth.begin(), smooth.end(), max_h);
            
            for (auto it = lo; it != hi; ++it) {
                ll area = w * (*it);
                area_cnt[area]++;
            }
        }
        
        // Update M
        for (auto& [area, cnt] : area_cnt) {
            if (cnt >= 2 && cnt <= N) {
                if (area < M[cnt]) {
                    if (M[cnt] == LLONG_MAX) found++;
                    M[cnt] = area;
                }
            }
        }
        
        limit *= 10;
    }
    
    i128 sum = 0;
    for (ll i = 2; i <= N; i++) {
        if (M[i] != LLONG_MAX) sum += M[i];
    }
    
    // Output
    string out;
    i128 temp = sum;
    if (temp == 0) out = "0";
    while (temp) { out = (char)('0' + (int)(temp % 10)) + out; temp /= 10; }
    cout << out << "\n";
    
    return 0;
}
