#include <bits/stdc++.h>
using namespace std;
using ll = long long;

// PE 946 (simple / reduced version): Continued Fraction Fraction / 连分数的分数
//
// α is the real number whose continued fraction is
//   α = [2; 1,1, 2, 1,1,1, 2, 1,1,1,1,1, 2, ...]
// where the number of 1's between consecutive 2's are the consecutive primes
// (2, 3, 5, 7, 11, ...).
//
// β = (2α + 3) / (3α + 2).
//
// Input:  a single integer N (1 <= N <= 10^6).
// Output: the sum of the first N coefficients of the continued fraction of β.
//
// Method: Gosper's algorithm for continued-fraction arithmetic.
// A Möbius transformation z -> (a·z + b)/(c·z + d) applied to a continued
// fraction can be streamed term by term. We feed α's terms (generated by the
// prime pattern) into the matrix [[2,3],[3,2]] and read out β's terms.
//
// Given sample: the first 10 coefficients of β are [0;1,5,6,16,9,1,10,16,11]
// with sum 75.

bool is_prime(ll n) {
    if (n < 2) return false;
    for (ll i = 2; i * i <= n; ++i)
        if (n % i == 0) return false;
    return true;
}

ll solve(ll N) {
    // Lazy generator for α's continued-fraction terms.
    // Terms: a_0 = 2, then for each prime p: p ones followed by a single 2.
    vector<ll> primes;      // primes generated lazily
    ll next_cand = 2;       // next candidate to test for primality
    ll alpha_emitted = 0;   // number of α terms emitted so far
    ll prime_idx = 0;       // index of the current prime run
    ll run_pos = 0;         // how many 1's of the current run already emitted

    auto next_alpha = [&]() -> ll {
        if (alpha_emitted == 0) {
            ++alpha_emitted;
            return 2;                       // integer part a_0 = 2
        }
        // make sure primes[prime_idx] exists
        while ((ll)primes.size() <= prime_idx) {
            while (!is_prime(next_cand)) ++next_cand;
            primes.push_back(next_cand);
            ++next_cand;
        }
        if (run_pos < primes[prime_idx]) {
            ++run_pos;
            ++alpha_emitted;
            return 1;                       // inside a run of 1's
        }
        // run finished: emit the separating 2 and move to the next prime
        run_pos = 0;
        ++prime_idx;
        ++alpha_emitted;
        return 2;
    };

    // State matrix Z = [[a, b], [c, d]] representing (a·x + b)/(c·x + d),
    // where x is the (unknown) tail of α's continued fraction.
    // Initially β = (2α + 3)/(3α + 2).
    ll a = 2, b = 3, c = 3, d = 2;

    ll sum = 0;
    ll out_count = 0;

    while (out_count < N) {
        if (c == 0 && d == 0) break;        // value fully determined (unreached)
        if (c == 0 || d == 0) {
            // degenerate state; ingest more input
            ll x = next_alpha();
            ll na = a * x + b, nb = a, nc = c * x + d, nd = c;
            a = na; b = nb; c = nc; d = nd;
            continue;
        }
        ll q1 = a / c;                      // floor(a/c), all values non-negative
        ll q2 = b / d;
        if (q1 == q2) {
            // emit one term of β's continued fraction
            sum += q1;
            ++out_count;
            // value -> 1/(value - q1):  Z <- [[c, d], [a - q1·c, b - q1·d]]
            ll na = c, nb = d;
            ll nc = a - q1 * c;
            ll nd = b - q1 * d;
            a = na; b = nb; c = nc; d = nd;
        } else {
            // ingest next α term:  Z <- Z · [[x, 1], [1, 0]]
            ll x = next_alpha();
            ll na = a * x + b, nb = a, nc = c * x + d, nd = c;
            a = na; b = nb; c = nc; d = nd;
        }
    }

    return sum;
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    ll N;
    cin >> N;
    cout << solve(N) << '\n';
    return 0;
}
