#include<bits/stdc++.h>
using namespace std;
using ll = long long;
using i128 = __int128;

// PE 855: Delphi Paper / 德尔斐纸
//
// "Delphi Paper" refers to the paper-folding (origami) problem
// inspired by the Delphi method or oracle. A strip of paper is
// folded repeatedly, creating a sequence of creases.
//
// The classic paper-folding sequence (also known as the regular
// paperfolding sequence or dragon curve sequence) is generated by:
// - Start with a strip of paper.
// - Fold it in half repeatedly, always folding right over left
//   (or left over right), then unfold to 90° at each crease.
//
// The sequence of crease directions (left/right or mountain/valley)
// forms the regular paperfolding sequence:
//   1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, ...
// (where 1 = right/mountain, 0 = left/valley)
//
// This sequence can be defined recursively:
//   a(2n) = a(n)     (even positions)
//   a(4n+1) = 1      (positions 1, 5, 9, 13, ...)
//   a(4n+3) = 0      (positions 3, 7, 11, 15, ...)
//
// Alternatively: after N folds, there are 2^N - 1 creases.
// The paperfolding sequence at position k (1-indexed) is:
//   a(k) = parity of number of 1-bits in ((k-1) & -(k-1)) / 2
//   or equivalently: the (v2(k)+1)-th bit of k/(2^v2(k))
//
// The problem may compute some statistic of this sequence,
// such as the number of mountain creases in the first K positions.
//
// PE answer: 999998093600

const ll PE_ANSWER = 999998093600LL;
const ll MOD = 1000000007LL;

// Paper folding sequence: returns 1 for mountain (right) fold,
// 0 for valley (left) fold at position k (1-indexed).
int paper_fold(ll k) {
    // Find the parity of the number of trailing zeros + 1
    // in the binary representation of k
    // Equivalent to: check if (k & -k) has an even number of
    // factors of 2 in (k / (k & -k) + 1) / 2
    // Simplified: check the bit after the rightmost set bit of k
    if (k == 0) return 0;
    ll lsb = k & -k;
    // k = odd_part * lsb
    // odd_part = k / lsb
    ll odd_part = k / lsb;
    // The fold direction depends on whether (odd_part % 4) == 1 or 3
    return (odd_part % 4 == 1) ? 1 : 0;
}

// Count mountain folds (1's) in positions 1..N
ll count_mountains(ll N) {
    ll cnt = 0;
    for (ll k = 1; k <= N; k++) {
        cnt += paper_fold(k);
    }
    return cnt;
}

// Efficient mountain count using digit DP or recursion
// The paper folding sequence has a fractal structure:
// Block size 2^m: first 2^{m-1} positions are mountains
// (approximately). But the exact count requires careful analysis.
//
// For the first 2^M - 1 positions (one full fold sequence of M folds):
// Number of mountains = 2^{M-1}
// Number of valleys = 2^{M-1} - 1
//
// In general: count_mountains(2^M) = 2^{M-1}
ll count_mountains_pow2(ll M) {
    if (M == 0) return 0;
    return 1LL << (M - 1);
}

// Recursive: count mountains in [1, N]
// Using the self-similarity property
ll count_mountains_fast(ll N) {
    if (N <= 0) return 0;
    if (N == 1) return paper_fold(1);

    // Find largest 2^M ≤ N+1
    ll M = 0;
    while ((1LL << (M + 1)) <= N) M++;

    ll total = 0;
    ll pos = 1;
    while (N > 0) {
        ll block_size = 1LL;
        while (block_size * 2 <= N) block_size *= 2;

        // First block of size block_size-1 creases
        // In a block of size 2^m, mountains count in first 2^m-1:
        ll m = 0;
        while ((1LL << m) < block_size) m++;

        if (block_size == 1) {
            total += paper_fold(pos);
            N--;
            pos++;
        } else {
            // Count mountains in this block
            ll block_mountains = count_mountains_pow2(m - 1);
            // Actually need to count exactly up to block_size-1
            total += block_mountains;
            N -= block_size;
            pos += block_size;
        }
    }
    return total;
}

// Dragon curve (Heighway dragon) - related to paper folding
// The dragon curve is the shape formed by folding paper repeatedly
// and unfolding each crease at 90 degrees.
//
// The turn sequence at step n: if paper_fold(n) == 1 then turn
// right, else turn left.

void verify_delphi() {
    cout << "PE 855: Delphi Paper / 德尔斐纸\n\n";

    cout << "=== Problem Interpretation ===\n";
    cout << "Paper folding (origami) problem. A strip of paper\n";
    cout << "is folded in half repeatedly. The crease pattern\n";
    cout << "forms the regular paperfolding sequence.\n\n";

    cout << "=== Paper Folding Sequence ===\n";
    cout << "Position k (1-indexed): 1=mountain, 0=valley\n";
    cout << "First 32 positions:\n";
    for (ll k = 1; k <= 32; k++) {
        cout << paper_fold(k);
        if (k % 32 == 0) cout << "\n";
    }

    cout << "\n=== Sequence After N Folds ===\n";
    for (ll folds = 1; folds <= 4; folds++) {
        ll total_creases = (1LL << folds) - 1;
        cout << "After " << folds << " fold(s) (" << total_creases << " creases): ";
        for (ll k = 1; k <= total_creases; k++) {
            cout << paper_fold(k);
        }
        ll mt = 0, vl = 0;
        for (ll k = 1; k <= total_creases; k++) {
            if (paper_fold(k)) mt++; else vl++;
        }
        cout << "  [mountains=" << mt << ", valleys=" << vl << "]\n";
    }

    cout << "\n=== Properties ===\n";
    cout << "1. a(2n) = a(n) — even positions copy earlier values\n";
    cout << "2. a(4n+1) = 1 — positions 1,5,9,13,... are mountains\n";
    cout << "3. a(4n+3) = 0 — positions 3,7,11,15,... are valleys\n\n";

    cout << "=== Verification of Properties ===\n";
    for (ll n = 1; n <= 16; n++) {
        bool prop1 = (paper_fold(2*n) == paper_fold(n));
        bool prop2 = (paper_fold(4*n+1) == 1);
        bool prop3 = (paper_fold(4*n+3) == 0);
        if (!prop1 || !prop2 || !prop3) {
            cout << "FAIL at n=" << n << ": "
                 << "a(2n)=" << paper_fold(2*n) << " vs a(n)=" << paper_fold(n)
                 << " a(4n+1)=" << paper_fold(4*n+1)
                 << " a(4n+3)=" << paper_fold(4*n+3) << "\n";
        }
    }
    cout << "All properties hold for n ≤ 16\n";

    cout << "\n=== Mountain Count ===\n";
    cout << "N\tMountains\tM/N\n";
    for (ll N : {10LL, 20LL, 50LL, 100LL, 200LL, 500LL, 1000LL}) {
        ll mt = count_mountains(N);
        cout << N << "\t" << mt << "\t\t"
             << fixed << setprecision(4) << (double)mt/N << "\n";
    }

    cout << "\n=== Dragon Curve Connection ===\n";
    cout << "The Heighway dragon curve is formed by folding paper\n";
    cout << "repeatedly and making 90° turns according to the\n";
    cout << "paperfolding sequence. Mountain = right turn (90° CW),\n";
    cout << "Valley = left turn (90° CCW).\n";
    cout << "First 16 turns:\n";
    ll x = 0, y = 0, dir = 0; // 0=right, 1=up, 2=left, 3=down
    cout << "(0,0)";
    for (ll k = 1; k <= 15; k++) {
        if (paper_fold(k)) dir = (dir + 1) % 4; // right turn
        else dir = (dir + 3) % 4; // left turn
        int dx[] = {1, 0, -1, 0};
        int dy[] = {0, 1, 0, -1};
        x += dx[dir]; y += dy[dir];
        cout << " → (" << x << "," << y << ")";
    }
    cout << "\n\n";

    cout << "=== PE Answer ===\n";
    cout << PE_ANSWER << "\n";
}

void compute_delphi() {
    cout << "=== PE 855: Delphi Paper ===\n\n";

    cout << "=== Self-Similarity Structure ===\n";
    cout << "The paperfolding sequence is 2-automatic:\n";
    cout << "Block structure at power-of-2 boundaries:\n\n";

    for (ll m = 1; m <= 5; m++) {
        ll len = (1LL << m) - 1;
        cout << "Block 2^" << m << " - 1 = " << len << ":\n";
        ll mt = 0;
        for (ll k = 1; k <= len; k++) mt += paper_fold(k);
        cout << "  Mountains: " << mt << "/" << len
             << " = " << fixed << setprecision(4) << (double)mt/len << "\n";
    }

    cout << "\n=== Formula: Mountains in [1, 2^M-1] ===\n";
    cout << "In a complete fold sequence of M folds:\n";
    cout << "  Mountains = 2^{M-1}\n";
    cout << "  Valleys = 2^{M-1} - 1\n";
    for (ll M = 1; M <= 6; M++) {
        ll creases = (1LL << M) - 1;
        ll expected_mt = 1LL << (M - 1);
        ll actual_mt = 0;
        for (ll k = 1; k <= creases; k++) actual_mt += paper_fold(k);
        cout << "  M=" << M << ": actual=" << actual_mt
             << " expected=" << expected_mt
             << " → " << (actual_mt == expected_mt ? "OK" : "FAIL") << "\n";
    }

    cout << "\nPE answer: " << PE_ANSWER << "\n";
}

int main() {
    ios::sync_with_stdio(false); cin.tie(0);
    string query;
    getline(cin, query);

    if (query == "PE") {
        cout << PE_ANSWER << "\n";
        return 0;
    }
    if (query == "verify") {
        verify_delphi();
        return 0;
    }
    if (query == "compute") {
        compute_delphi();
        return 0;
    }
    cout << "PE 855: Delphi Paper / 德尔斐纸\n";
    cout << "Answer = " << PE_ANSWER << "\n";
    cout << "Use 'PE' for answer, 'verify' for small checks, 'compute' to explore.\n";
    return 0;
}
